CREATE DATABASE CHHS
GO
----------------------------
----------------------------
USE CHHS
GO
-----------------------------------
---BRANCH_TABLE
CREATE TABLE BRANCH(
	ID_BRA nchar(25) PRIMARY KEY,
	NAME_BRA nvarchar(255) UNIQUE,
	ADDR nvarchar(255),
	NUM nchar(25)
)

---CUSTOMER_TABLE
CREATE TABLE CUSTOMER(
	ID_CUS nchar(25) PRIMARY KEY not null,
	FULLNAME nvarchar(255),
	ADDR nvarchar(255),
	NUM nchar(25),
	ID_BRA nchar(25) FOREIGN KEY (ID_BRA) REFERENCES BRANCH(ID_BRA) ON UPDATE CASCADE
)

---STORAGE_TABLE
CREATE TABLE STORAGE(
	ID_STO nchar(25) PRIMARY KEY,
	NAME_STO nvarchar(255) UNIQUE,
	ADDR nvarchar(255),
	ID_BRA nchar(25) FOREIGN KEY (ID_BRA) REFERENCES BRANCH(ID_BRA) ON UPDATE CASCADE 
)

---EMPLOYEE_TABLE
CREATE TABLE EMPLOYEE(
	ID_EMP char(25) PRIMARY KEY not null,
	FULLNAME nvarchar(255),
	AGE int,
	ADDR nvarchar(255),
	SAL float CHECK(SAL > 5000000.0),
	ID_BRA nchar(25) FOREIGN KEY (ID_BRA) REFERENCES BRANCH(ID_BRA) ON UPDATE CASCADE 
)

---GOODS_TABLE
CREATE TABLE SEAFOOD(
	ID_SEA char(25) PRIMARY KEY not null,
	NAME_SEA nvarchar(255),
	PRICE float,
	SUPPLIER nvarchar(255),
	INSTOCK float CHECK(INSTOCK > 0.0)
)

---INVOICE_TABLE
CREATE TABLE INVOICE(
	ID_INV int PRIMARY KEY not null,
	TIME_DATE smalldatetime DEFAULT(GETDATE()),
	TOTALPRICE float,
	ID_CUS nchar(25) FOREIGN KEY (ID_CUS) REFERENCES CUSTOMER(ID_CUS),
	ID_EMP char(25) FOREIGN KEY (ID_EMP) REFERENCES EMPLOYEE(ID_EMP),
	ID_STO nchar(25) FOREIGN KEY (ID_STO) REFERENCES STORAGE(ID_STO) ON UPDATE CASCADE
)

---INVOICE_DETAIL_TABLE
CREATE TABLE INVOICE_DETAIL(
	ID_INV int FOREIGN KEY (ID_INV) REFERENCES INVOICE(ID_INV) ON UPDATE CASCADE,
	ID_SEA char(25) FOREIGN KEY (ID_SEA) REFERENCES SEAFOOD(ID_SEA) ON UPDATE CASCADE,
	AMOUNT float CHECK (AMOUNT > 0.0)
)

---RECEIPT_NOTE_TABLE
CREATE TABLE RECEIPT_NOTE(
	ID_REC int PRIMARY KEY,
	DATE_TIME date DEFAULT(GETDATE()),
	SOURCE nvarchar(255),
	TOTALPRICE float,
	ID_EMP char(25) FOREIGN KEY (ID_EMP) REFERENCES EMPLOYEE(ID_EMP),
	ID_STO nchar(25) FOREIGN KEY (ID_STO) REFERENCES STORAGE(ID_STO) ON UPDATE CASCADE
)

---RECEIPT_DETAIL_TABLE
CREATE TABLE RECEIPT_DETAIL(
	ID_REC int FOREIGN KEY (ID_REC) REFERENCES RECEIPT_NOTE(ID_REC) ON UPDATE CASCADE,
	ID_SEA char(25) FOREIGN KEY (ID_SEA) REFERENCES SEAFOOD(ID_SEA) ON UPDATE CASCADE,
	AMOUNT float CHECK (AMOUNT > 0.0),
	PRICE float
)